### ISSUE TITLE
Python API on MS Learn not in use?

### ISSUE THREAD

**Issue by kexugit** [microsoft/project-freta#61]
Hi, Project Freta owners, 

We are the Learn engieering team for API reference documentation. We found that the previously released package “freta” was taken offline from pypi. And the Python SDK is also removed from the github repo. The SDK has been rewritten in Rust. With all of these changes, our reference generation pipeline cannot consume the python package and failed to rebuild the API documents. 

Based on the current documentation list, it seems that https://learn.microsoft.com/en-us/python/api/freta/ is not in use anymore. Please help confirm so that we can remove the CI job for publishing, and removed the  outdated API from Learn.microsoft.com. 

Thank you!

**Comment by demoray** [comment]
The python API is no longer in use.  Thanks!
